SELECT CAB.NUNOTA,CAB.CODPARC,CAB.CODEMP,CAB.NUMNOTA,CAB.CODVEND,CAB.DTNEG,CAB.DTMOV,CAB.DTFATUR,CAB.CODTIPVENDA,CAB.SERIENOTA,CAB.CHAVENFE,CAB.VLRNOTA
FROM TGFCAB CAB
WHERE CODTIPOPER = 1152
  AND NOT EXISTS ( SELECT 1
                   FROM TGFCAB
                   WHERE CODTIPOPER = 1452
                     AND NUMNOTA = CAB.NUMNOTA
                     AND CODEMP = CAB.CODPARC
                     AND CODPARC = CAB.CODEMP
                     AND CHAVENFE = CAB.CHAVENFE )
  AND CAB.STATUSNOTA = 'L'
  AND CAB.STATUSNFE = 'A'
-- AND CAB.NUNOTA = 7375